### ISSUE TITLE
Polluted state when navigating back and forth on planning poker

### ISSUE THREAD

**Issue by yduman** [MaibornWolff/retro#108]

**Comment by yduman** [comment]
Remember to always provide a description duh... Can't remember where the issue was and can't reproduce anymore. Closing.

**Comment by sillydomnom** [comment]
Actually I can reproduce this issue. When reloading a session you can still change your votes even after reloading the page. Then pictures like these can occur: 
![image](https://user-images.githubusercontent.com/18489820/143836730-17225dca-5e78-40cf-b9ee-83488c8918b4.png)

**Comment by yduman** [comment]
Interesting. Could you provide a step-by-step description in order to have something reproducible? Thanks!
