### ISSUE TITLE
Add timeboxing

### ISSUE THREAD

**Issue by yduman** [MaibornWolff/retro#54]
You can trigger timeboxing by a mechanism (e.g. button) in order to start a timer, which runs as long as the user defined.

**Comment by Nomandes** [comment]
Additionally it would be great if a running Timer could be extended if more time is needed (+/-1) and if the voting could be coupled with a timer, so that the voting is possible while the timer runs

**Comment by Nomandes** [comment]
Feature is implemented and in review
